########################################################################################################################
# LOCAL
########################################################################################################################

## @section Local parameters
## @param nameOverride Override name
nameOverride: edusharing-services-rendering2

########################################################################################################################
# DEPENDENCY
########################################################################################################################

edusharing_services_rendering2_rabbitmq:

  ## @param edusharing_services_rendering2_rabbitmq.enabled Enable rabbitmq
  enabled: true

  image:
    ## @param edusharing_services_rendering2_rabbitmq.image.name Set rabbitmq image name
    name: ${docker.edu_sharing.community.common.rabbitmq.name}
    ## @param edusharing_services_rendering2_rabbitmq.image.tag Set rabbitmq image tag
    tag: ${docker.edu_sharing.community.common.rabbitmq.tag}

  ## @param edusharing_services_rendering2_rabbitmq.nameOverride Override rabbitmq name
  nameOverride: &rabbitmqNameOverride edusharing-services-rendering2-rabbitmq

  service:
    port:
      ## @param edusharing_services_rendering2_rabbitmq.service.port.amqp Set rabbitmq service amqp port
      amqp: &rabbitmqServicePortAmqp 5672

  config:
    ## @param edusharing_services_rendering2_rabbitmq.config.username Set mongodb username
    username: &rabbitmqConfigUsername rendering2

  init:

    permission:

      image:
        ## @param edusharing_services_rendering2_rabbitmq.init.permission.image.name Set rabbitmq init permission image name
        name: ${docker.edu_sharing.community.common.minideb.name}
        ## @param edusharing_services_rendering2_rabbitmq.init.permission.image.tag Set rabbitmq init permission image tag
        tag: ${docker.edu_sharing.community.common.minideb.tag}

    plugins:

      image:
        ## @param edusharing_services_rendering2_rabbitmq.init.plugins.image.name Set rabbitmq init plugins image name
        name: ${docker.edu_sharing.community.common.rabbitmq.name}
        ## @param edusharing_services_rendering2_rabbitmq.init.plugins.image.tag Set rabbitmq init plugins image tag
        tag: ${docker.edu_sharing.community.common.rabbitmq.tag}

########################################################################################################################

edusharing_services_rendering2_storage:

  ## @param edusharing_services_rendering2_storage.nameOverride Override storage name
  nameOverride: &storageNameOverride edusharing-services-rendering2-storage

  service:

    port:
      ## @param edusharing_services_rendering2_storage.service.port.api Set storage service api port
      api: &storageServicePortApi 9000

  config:

    ## @param edusharing_services_rendering2_storage.config.protocol Set storage protocol
    protocol: &storageConfigProtocol http

    ## @param edusharing_services_rendering2_storage.config.region Set storage region
    region: &storageConfigRegion eu-central-1

    ## @param edusharing_services_rendering2_storage.config.username Set storage username
    username: &storageConfigUsername rendering2

########################################################################################################################

edusharing_services_rendering2_storage_minio:

  ## @param edusharing_services_rendering2_storage_minio.enabled Enable minio
  enabled: false

  ## @param edusharing_services_rendering2_storage_minio.nameOverride Override minio name
  nameOverride: *storageNameOverride

  image:
    ## @param edusharing_services_rendering2_storage_minio.image.name Set minio image name
    name: ${docker.edu_sharing.community.common.minio.name}
    ## @param edusharing_services_rendering2_storage_minio.image.tag Set minio image tag
    tag: ${docker.edu_sharing.community.common.minio.tag}

  service:

    port:
      ## @param edusharing_services_rendering2_storage_minio.service.port.api Set minio service api port
      api: *storageServicePortApi

  config:

    ## @param edusharing_services_rendering2_storage_minio.config.buckets Set minio buckets
    buckets: []

    notify:

      ## @param edusharing_services_rendering2_storage_minio.config.notify.amqp Set minio amqp notify targets
      amqp: []

    ## @param edusharing_services_rendering2_storage_minio.config.username Set minio username
    username: *storageConfigUsername

  init:

    permission:

      image:
        ## @param edusharing_services_rendering2_storage_minio.init.permission.image.name Set minio init permission image name
        name: ${docker.edu_sharing.community.common.minideb.name}
        ## @param edusharing_services_rendering2_storage_minio.init.permission.image.tag Set minio init permission image tag
        tag: ${docker.edu_sharing.community.common.minideb.tag}

  job:

    provisioning:

      init:

        wait:

          image:
            ## @param edusharing_services_rendering2_storage_minio.job.provisioning.init.wait.image.name Set wait container image name
            name: ${docker.edu_sharing.community.common.minideb.name}
            ## @param edusharing_services_rendering2_storage_minio.job.provisioning.init.wait.image.tag Set wait container image tag
            tag: ${docker.edu_sharing.community.common.minideb.tag}

      image:
        ## @param edusharing_services_rendering2_storage_minio.job.provisioning.image.name Set job image name
        name: ${docker.edu_sharing.community.common.minio.name}
        ## @param edusharing_services_rendering2_storage_minio.job.provisioning.image.tag Set job image tag
        tag: ${docker.edu_sharing.community.common.minio.tag}

########################################################################################################################

edusharing_services_rendering2_storage_rustfs:

  ## @param edusharing_services_rendering2_storage_rustfs.enabled Enable rustfs
  enabled: true

  ## @param edusharing_services_rendering2_storage_rustfs.nameOverride Override rustfs name
  nameOverride: *storageNameOverride

  image:
    ## @param edusharing_services_rendering2_storage_rustfs.image.name Set rustfs image name
    name: ${docker.edu_sharing.community.common.rustfs.name}
    ## @param edusharing_services_rendering2_storage_rustfs.image.tag Set rustfs image tag
    tag: ${docker.edu_sharing.community.common.rustfs.tag}

  service:

    port:
      ## @param edusharing_services_rendering2_storage_rustfs.service.port.api Set rustfs service api port
      api: *storageServicePortApi

  config:

    ## @param edusharing_services_rendering2_storage_rustfs.config.username Set rustfs username
    username: *storageConfigUsername

  init:

    permission:

      image:
        ## @param edusharing_services_rendering2_storage_rustfs.init.permission.image.name Set rustfs init permission image name
        name: ${docker.edu_sharing.community.common.minideb.name}
        ## @param edusharing_services_rendering2_storage_rustfs.init.permission.image.tag Set rustfs init permission image tag
        tag: ${docker.edu_sharing.community.common.minideb.tag}

########################################################################################################################

edusharing_services_rendering2_mongodb:

  ## @param edusharing_services_rendering2_mongodb.enabled Enable mongodb
  enabled: true

  ## @param edusharing_services_rendering2_mongodb.nameOverride Override mongodb name
  nameOverride: &mongoNameOverride edusharing-services-rendering2-mongodb

  image:
    ## @param edusharing_services_rendering2_mongodb.image.name Set mongodb image name
    name: ${docker.edu_sharing.community.common.mongodb.name}
    ## @param edusharing_services_rendering2_mongodb.image.tag Set mongodb image tag
    tag: ${docker.edu_sharing.community.common.mongodb.tag}

  service:
    port:
      ## @param edusharing_services_rendering2_mongodb.service.port.api Set mongodb service api port
      api: &mongoServicePortApi 27017

  config:
    ## @param edusharing_services_rendering2_mongodb.config.database Set mongodb database
    database: &mongoConfigDatabase rendering2
    ## @param edusharing_services_rendering2_mongodb.config.username Set mongodb username
    username: &mongoConfigUsername rendering2

    extra:
      ## @param edusharing_services_rendering2_mongodb.config.extra.databases Set extra mongodb databases
      databases: &mongoLumiConfigDatabase lumi
      ## @param edusharing_services_rendering2_mongodb.config.extra.usernames Set extra mongodb usernames
      usernames: &mongoLumiConfigUsername lumi

  init:

    permission:

      image:
        ## @param edusharing_services_rendering2_mongodb.init.permission.image.name Set mongodb init permission image name
        name: ${docker.edu_sharing.community.common.minideb.name}
        ## @param edusharing_services_rendering2_mongodb.init.permission.image.tag Set mongodb init permission image tag
        tag: ${docker.edu_sharing.community.common.minideb.tag}

  job:

    dump:

      image:
        ## @param edusharing_services_rendering2_mongodb.job.dump.image.name Set mongodb dump job image name
        name: ${docker.edu_sharing.community.common.mongodb.name}
        ## @param edusharing_services_rendering2_mongodb.job.dump.image.tag Set mongodb dump job image tag
        tag: ${docker.edu_sharing.community.common.mongodb.tag}

  sidecar:

    metrics:

      image:
        ## @param edusharing_services_rendering2_mongodb.sidecar.metrics.image.name Set metrics sidecar image name
        name: ${docker.edu_sharing.community.common.mongodb.exporter.name}
        ## @param edusharing_services_rendering2_mongodb.sidecar.metrics.image.tag Set metrics sidecar image tag
        tag: ${docker.edu_sharing.community.common.mongodb.exporter.tag}

########################################################################################################################

edusharing_services_rendering2_rediscluster:

  ## @param edusharing_services_rendering2_rediscluster.enabled Enable rediscluster
  enabled: true

  image:
    ## @param edusharing_services_rendering2_rediscluster.image.name Set rediscluster image name
    name: ${docker.edu_sharing.community.common.redis-cluster.name}
    ## @param edusharing_services_rendering2_rediscluster.image.tag Set rediscluster image tag
    tag: ${docker.edu_sharing.community.common.redis-cluster.tag}

  ## @param edusharing_services_rendering2_rediscluster.nameOverride Override rediscluster name
  nameOverride: &redisclusterNameOverride edusharing-services-rendering2-rediscluster

  service:
    port:
      ## @param edusharing_services_rendering2_rediscluster.service.port.api Set rediscluster service api port
      api: &redisclusterServicePortApi 6379

  init:

    permission:

      image:
        ## @param edusharing_services_rendering2_rediscluster.init.permission.image.name Set rediscluster init permission image name
        name: ${docker.edu_sharing.community.common.minideb.name}
        ## @param edusharing_services_rendering2_rediscluster.init.permission.image.tag Set rediscluster init permission image tag
        tag: ${docker.edu_sharing.community.common.minideb.tag}

    sysctl:

      image:
        ## @param edusharing_services_rendering2_rediscluster.init.sysctl.image.name Set rediscluster init sysctl image name
        name: ${docker.edu_sharing.community.common.minideb.name}
        ## @param edusharing_services_rendering2_rediscluster.init.sysctl.image.tag Set rediscluster init sysctl image tag
        tag: ${docker.edu_sharing.community.common.minideb.tag}

  sidecar:

    metrics:

      image:
        ## @param edusharing_services_rendering2_rediscluster.sidecar.metrics.image.name Set rediscluster sidecar metrics image name
        name: ${docker.edu_sharing.community.common.redis.exporter.name}
        ## @param edusharing_services_rendering2_rediscluster.sidecar.metrics.image.tag Set rediscluster sidecar metrics image tag
        tag: ${docker.edu_sharing.community.common.redis.exporter.tag}

########################################################################################################################

edusharing_services_rendering2_document_converter:

  ## @param edusharing_services_rendering2_document_converter.enabled Enable rendering2 document converter
  enabled: true

  ## @param edusharing_services_rendering2_document_converter.nameOverride Override rendering2 document converter name
  nameOverride: &documentConverterNameOverride edusharing-services-rendering2-document-converter

  service:
    port:
      ## @param edusharing_services_rendering2_document_converter.service.port.api Set rendering2 document converter service api port
      api: &documentConverterServicePortApi 8080

########################################################################################################################

edusharing_services_rendering2_jupyter_converter:

  ## @param edusharing_services_rendering2_jupyter_converter.enabled Enable rendering2 jupyter converter
  enabled: true

  ## @param edusharing_services_rendering2_jupyter_converter.nameOverride Override rendering2 jupyter converter name
  nameOverride: &jupyterConverterNameOverride edusharing-services-rendering2-jupyter-converter

  service:
    port:
      ## @param edusharing_services_rendering2_jupyter_converter.service.port.api Set rendering2 jupyter converter service api port
      api: &jupyterConverterServicePortApi 8000

########################################################################################################################

edusharing_services_rendering2_lumi:

  ## @param edusharing_services_rendering2_lumi.enabled Enable rendering2 lumi
  enabled: true

  config:

    mongodb:
      ## @param edusharing_services_rendering2_lumi.config.mongodb.host Set mongodb host
      host: *mongoNameOverride
      ## @param edusharing_services_rendering2_lumi.config.mongodb.port Set mongodb port
      port: *mongoServicePortApi
      ## @param edusharing_services_rendering2_lumi.config.mongodb.username Set mongodb username
      username: *mongoLumiConfigUsername
      ## @param edusharing_services_rendering2_lumi.config.mongodb.database Set mongodb database
      database: *mongoLumiConfigDatabase


    s3:
      ## @param edusharing_services_rendering2_lumi.config.s3.host Set S3 host
      host: *storageNameOverride
      ## @param edusharing_services_rendering2_lumi.config.s3.port Set S3 port
      port: *storageServicePortApi
      ## @param edusharing_services_rendering2_lumi.config.s3.protocol Set S3 protocol
      protocol: *storageConfigProtocol
      ## @param edusharing_services_rendering2_lumi.config.s3.region Set S3 region
      region: *storageConfigRegion
      ## @param edusharing_services_rendering2_lumi.config.s3.username Set S3 username
      username: *storageConfigUsername

########################################################################################################################

edusharing_services_rendering2_service:

  ## @param edusharing_services_rendering2_service.enabled Enable rendering2 service
  enabled: true

  config:

    converter:
      document:
        ## @param edusharing_services_rendering2_service.config.converter.document.host Set document-converter host
        host: *documentConverterNameOverride
        ## @param edusharing_services_rendering2_service.config.converter.document.port Set document-converter port
        port: *documentConverterServicePortApi
      jupyter:
        ## @param edusharing_services_rendering2_service.config.converter.jupyter.host Set jupyter-converter host
        host: *jupyterConverterNameOverride
        ## @param edusharing_services_rendering2_service.config.converter.jupyter.port Set jupyter-converter port
        port: *jupyterConverterServicePortApi

    mongodb:
      ## @param edusharing_services_rendering2_service.config.mongodb.host Set mongodb host
      host: *mongoNameOverride
      ## @param edusharing_services_rendering2_service.config.mongodb.port Set mongodb port
      port: *mongoServicePortApi
      ## @param edusharing_services_rendering2_service.config.mongodb.username Set mongodb username
      username: *mongoConfigUsername
      ## @param edusharing_services_rendering2_service.config.mongodb.database Set mongodb database
      database: *mongoConfigDatabase

    rabbitmq:
      ## @param edusharing_services_rendering2_service.config.rabbitmq.host Set rabbitmq host
      host: *rabbitmqNameOverride
      ## @param edusharing_services_rendering2_service.config.rabbitmq.port Set rabbitmq port
      port: *rabbitmqServicePortAmqp
      ## @param edusharing_services_rendering2_service.config.rabbitmq.username Set rabbitmq username
      username: *rabbitmqConfigUsername

    redis:
      ## @param edusharing_services_rendering2_service.config.redis.host Set redis host
      host: *redisclusterNameOverride
      ## @param edusharing_services_rendering2_service.config.redis.port Set redis port
      port: *redisclusterServicePortApi

    s3:
      ## @param edusharing_services_rendering2_service.config.s3.host Set S3 host
      host: *storageNameOverride
      ## @param edusharing_services_rendering2_service.config.s3.port Set S3 port
      port: *storageServicePortApi
      ## @param edusharing_services_rendering2_service.config.s3.username Set S3 username
      username: *storageConfigUsername
      ## @param edusharing_services_rendering2_service.config.s3.protocol Set S3 protocol
      protocol: *storageConfigProtocol
      ## @param edusharing_services_rendering2_service.config.s3.region Set S3 region
      region: *storageConfigRegion

########################################################################################################################
