version: '3.8'

services:

  minio:
    image: docker.edu-sharing.com/community/common/edu_sharing-community-common-docker-minio:2024.11.7
    ports:
      - "9101:9000"
      - "9111:9001"
    environment:
      MINIO_ROOT_USER: "rendering2"
      MINIO_ROOT_PASSWORD: "rendering2"
      MINIO_DEFAULT_BUCKETS: lumi-contentbucket,lumi-tempbucket,lumi-libbucket
#    volumes:
#      - "minio-data-volume:/bitnami/minio/data"

  repository-cache:
    image: docker.edu-sharing.com/community/common/edu_sharing-community-common-docker-redis:6.2.7
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "9109:6379"

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: "rendering"
      RABBITMQ_DEFAULT_PASS: "rendering"
      RABBITMQ_SECURE_PASSWORD: true
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: true
    ports:
      - "9104:5672"
      - "15672:15672"

  mongo:
    image: "docker.edu-sharing.com/community/common/edu_sharing-community-common-docker-mongodb:7.0.15"
    environment:
      MONGODB_ROOT_USER: admin
      MONGODB_ROOT_PASSWORD: admin
      MONGODB_EXTRA_RENDERING2_DATABASE: "rendering"
      MONGODB_EXTRA_RENDERING2_USERNAME: "rendering"
      MONGODB_EXTRA_RENDERING2_PASSWORD: "rendering"
      MONGODB_EXTRA_LUMI_DATABASE: "lumi"
      MONGODB_EXTRA_LUMI_USERNAME: "lumi"
      MONGODB_EXTRA_LUMI_PASSWORD: "lumi"
    ports:
      - "9106:27017"

  rendering2-document-converter:
    image: "docker.edu-sharing.com/community/edu_sharing-community-services-rendering2-deploy-docker-build-document-converter:maven-fixes-10.0-SNAPSHOT"
    command:
      - -Xms${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMS:-512m}
      - -Xmx${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMX:-512m}
      - -Dcom.sun.management.jmxremote
      - -Dcom.sun.management.jmxremote.authenticate=false
      - -Dcom.sun.management.jmxremote.port=7199
      - -Dcom.sun.management.jmxremote.ssl=false
    ports:
      - "8081:8080"

  rendering2-jupyter-converter:
    image: "docker.edu-sharing.com/community/edu_sharing-community-services-rendering2-deploy-docker-build-jupyter-converter:maven-fixes-10.0-SNAPSHOT"
    ports:
      - "9120:8000"

  rendering2-lumi:
    image: "docker.edu-sharing.com/community/edu_sharing-community-services-rendering2-deploy-docker-build-lumi:maven-fixes-10.0-SNAPSHOT"
    environment:
      AWS_ACCESS_KEY_ID: rendering2
      AWS_SECRET_ACCESS_KEY: rendering2
      MINIO_HOST: minio
      MINIO_PORT: 9000
      AWS_S3_MAX_FILE_LENGTH: 1000
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
      MONGODB_AUTH_DB: "lumi"
      MONGODB_DB: "lumi"
      MONGODB_USER: "lumi"
      MONGODB_PASSWORD: "lumi"
      CONTENT_AWS_S3_BUCKET: lumi-contentbucket
      CONTENT_MONGO_COLLECTION: h5p
      TEMPORARY_AWS_S3_BUCKET: lumi-tempbucket
      LIBRARY_MONGO_COLLECTION: h5plibraries
      LIBRARY_AWS_S3_BUCKET: lumi-libbucket
      USERDATA_MONGO_COLLECTION: userdata
      FINISHED_MONGO_COLLECTION: finisheddata
      EDUSHARING_MONGO_COLLECTION: edusharing
      BASE_URL: /public/h5p
      CACHE: in-memory
      LOG_LEVEL: debug
      LOG_SCOPE: h5p:*
    ports:
      - "9112:3000"


  onix-service:
    image: "docker.edu-sharing.com/community/common/edu_sharing-community-common-docker-onyx:2025.05.1-0"
    environment:
      CATALINA_OPTS: >-
        -Xms${REPOSITORY_SERVICE_JAVA_XMS:-500m}
        -Xmx${REPOSITORY_SERVICE_JAVA_XMX:-1g}
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.port=7199
        -Dcom.sun.management.jmxremote.ssl=false
        -javaagent:/opt/onyx/tomcat/agent/jmx_prometheus_javaagent.jar=9090:/opt/onyx/tomcat/agent/jmx-exporter-config.yaml
      ONYX_SERVICE_PROT_EXTERNAL: "${ONYX_SERVICE_PROT_EXTERNAL:-http}"
      ONYX_SERVICE_HOST_EXTERNAL: "${ONYX_SERVICE_HOST_EXTERNAL:-onyx.127.0.0.1.nip.io}"
      ONYX_SERVICE_PORT_EXTERNAL: "${ONYX_SERVICE_PORT_EXTERNAL:-15080}"
      ONYX_SERVICE_PATH_EXTERNAL: "${ONYX_SERVICE_PATH_EXTERNAL:-/onyxplayer}"
      ALLOW_EMPTY_PASSWORD: "yes"
    expose:
      - "8080"
    ports:
      - "15100:8080"

#volumes:
#  minio-data-volume:
