<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.edu_sharing</groupId>
    <artifactId>edu_sharing-super-pom</artifactId>
    <version>22</version>
    <relativePath/>
  </parent>

  <artifactId>edu_sharing-community-services-rendering2</artifactId>
  <version>git</version>
  <packaging>pom</packaging>

  <name>edu_sharing-community-services-rendering2</name>

  <properties>
    <java.version>21</java.version>
    <kotlin.version>2.4.0</kotlin.version>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <docker.image.name>enterprise/edu_sharing-community-services-rendering2</docker.image.name>
    <docker.registry>docker.edu-sharing.com</docker.registry>


    <!-- release-2 -->
    <bom.repository.version>11.0.0-RC30</bom.repository.version>

  </properties>

  <scm>
    <connection>
      scm:git:https://scm.edu-sharing.com/edu-sharing/community/services/edu-sharing-community-services-rendering2.git
    </connection>
    <developerConnection>
      scm:git:https://scm.edu-sharing.com/edu-sharing/community/services/edu-sharing-community-services-rendering2.git
    </developerConnection>
    <url>
      https://scm.edu-sharing.com/edu-sharing/community/services/edu-sharing-community-services-rendering2.git
    </url>
  </scm>

  <profiles>
    <profile>
      <id>dev</id>
      <activation>
        <activeByDefault>false</activeByDefault>
        <property>
          <name>env.DEV</name>
          <value>true</value>
        </property>
      </activation>
      <properties>
        <edu-sharing.project>enterprise-</edu-sharing.project>
        <bom.repository.version>${edu-sharing.project}${project.version}</bom.repository.version>
      </properties>
    </profile>
  </profiles>

  <build>
    <plugins>

      <plugin>
        <groupId>com.github.tommyk-gears</groupId>
        <artifactId>bom-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>community-repository</id>
            <goals>
              <goal>import-properties</goal>
            </goals>
            <phase>validate</phase>
            <configuration>
              <artifacts>
                <dependency>
                  <groupId>${project.groupId}</groupId>
                  <artifactId>edu_sharing-community-repository</artifactId>
                  <!--suppress UnresolvedMavenProperty -->
                  <version>${bom.repository.version}</version>
                  <type>pom</type>
                </dependency>
              </artifacts>
            </configuration>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>

  <dependencyManagement>
    <dependencies>

      <dependency>
        <groupId>org.edu_sharing</groupId>
        <artifactId>edu_sharing-community-repository-backend-services-rest-client-java</artifactId>
        <version>${bom.repository.version}</version>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>edu_sharing-community-services-rendering2-service</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>edu_sharing-community-services-rendering2-document-converter</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>edu_sharing-community-services-rendering2-jupyter-converter</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>org.edu_sharing</groupId>
        <artifactId>edu_sharing-community-common-deployment-mongodb-compose</artifactId>
        <version>7.0.2</version>
      </dependency>

      <dependency>
        <groupId>org.edu_sharing</groupId>
        <artifactId>edu_sharing-community-common-deployment-onyx-compose</artifactId>
        <version>2025.05.1-0</version>
      </dependency>

      <dependency>
        <groupId>org.edu_sharing</groupId>
        <artifactId>edu_sharing-community-common-deployment-redis-cluster-compose</artifactId>
        <version>6.2-1</version>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>edu_sharing-community-services-rendering2-deploy-docker-compose</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>edu_sharing-community-services-rendering2-deploy-docker-helm-bundle</artifactId>
        <version>${project.version}</version>
        <type>tar.gz</type>
        <classifier>bin</classifier>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>edu_sharing-community-services-rendering2-deploy-docker-helm-document-converter</artifactId>
        <version>${project.version}</version>
        <type>tar.gz</type>
        <classifier>bin</classifier>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>edu_sharing-community-services-rendering2-deploy-docker-helm-jupyter-converter</artifactId>
        <version>${project.version}</version>
        <type>tar.gz</type>
        <classifier>bin</classifier>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>edu_sharing-community-services-rendering2-deploy-docker-helm-lumi</artifactId>
        <version>${project.version}</version>
        <type>tar.gz</type>
        <classifier>bin</classifier>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>edu_sharing-community-services-rendering2-deploy-docker-helm-service</artifactId>
        <version>${project.version}</version>
        <type>tar.gz</type>
        <classifier>bin</classifier>
      </dependency>

      <dependency>
        <groupId>org.testcontainers</groupId>
        <artifactId>testcontainers-bom</artifactId>
        <version>2.0.5</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!--
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>edu_sharing-community-services-rendering2-jupyter-converter</artifactId>
        <version>${project.version}</version>
      </dependency>
      -->
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>edu_sharing-community-services-rendering2-lumi</artifactId>
        <version>${project.version}</version>
        <classifier>bin</classifier>
        <type>zip</type>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>edu_sharing-community-services-rendering2-admin-frontend</artifactId>
        <version>${project.version}</version>
        <classifier>bin</classifier>
        <type>zip</type>
      </dependency>

      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>edu_sharing-community-services-rendering2-deploy-docker-helm-admin-frontend</artifactId>
        <version>${project.version}</version>
        <type>tar.gz</type>
        <classifier>bin</classifier>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <repositories>
    <repository>
      <id>edusharing-remote</id>
      <url>https://artifacts.edu-sharing.com/repository/maven-remote/</url>
      <releases>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
      </releases>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>never</updatePolicy>
      </snapshots>
    </repository>

    <repository>
      <id>edusharing-mirror</id>
      <url>https://artifacts.edu-sharing.com/repository/maven-mirror/</url>
      <releases>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
      </releases>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>never</updatePolicy>
      </snapshots>
    </repository>

  </repositories>

  <modules>
    <module>deploy</module>
    <module>service</module>
    <module>document-converter</module>
    <module>jupyter-converter</module>
    <module>lumi</module>
    <module>admin-frontend</module>
  </modules>
</project>
