version: '3.7'

services:
  rendering2-blob-storage:
    restart: unless-stopped

  rendering2-cache:
    restart: unless-stopped

  rendering2-message-queue:
    restart: unless-stopped

  rendering2-service:
    restart: unless-stopped

  rendering2-lumi:
    restart: unless-stopped
