version: '3.7'

services:

  rendering2-blob-storage:
    image: "${docker.registry}/${docker.common}/${docker.edu_sharing.community.common.minio.name}:${docker.edu_sharing.community.common.minio.tag}"
    environment:
      MINIO_ROOT_USER: "${RENDERING2_BLOB_STORAGE_USER:-rendering2}"
      MINIO_ROOT_PASSWORD: "${RENDERING2_BLOB_STORAGE_PASSWORD:-rendering2}"
      MINIO_DEFAULT_BUCKETS: contentbucket,tempbucket,libbucket
    volumes:
      - "rendering2-blob-storage-volume-data:/bitnami/minio/data"
    expose:
      - 9000
      - 9001
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING2_BLOB_STORAGE_PORT_HTTP:-10201}:9001"

  rendering2-message-queue:
    image: "${docker.registry}/${docker.common}/${docker.edu_sharing.community.common.rabbitmq.name}:${docker.edu_sharing.community.common.rabbitmq.tag}"
    environment:
      RABBITMQ_DEFAULT_USER: "${RENDERING2_MESSAGE_QUEUE_USER:-rendering}"
      RABBITMQ_DEFAULT_PASS: "${RENDERING2_MESSAGE_QUEUE_PASSWORD:-rendering}"
      RABBITMQ_SECURE_PASSWORD: true
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: true
    expose:
      - "5672"
      - "15672"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING2_MESSAGE_QUEUE_PORT_HTTP:-10300}:15672"

  mongo-database:
    environment:
      MONGODB_EXTRA_RENDERING2_DATABASE: "${RENDERING2_SERVICE_DATABASE_NAME:-rendering}"
      MONGODB_EXTRA_RENDERING2_USERNAME: "${RENDERING2_SERVICE_DATABASE_USER:-rendering}"
      MONGODB_EXTRA_RENDERING2_PASSWORD: "${RENDERING2_SERVICE_DATABASES_PASS:-rendering}"
      MONGODB_EXTRA_LUMI_DATABASE: "${RENDERING2_LUMI_DATABASE_NAME:-lumi}"
      MONGODB_EXTRA_LUMI_USERNAME: "${RENDERING2_LUMI_DATABASE_USER:-lumi}"
      MONGODB_EXTRA_LUMI_PASSWORD: "${RENDERING2_LUMI_DATABASE_PASS:-lumi}"

  rendering2-service:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-build-service:${docker.tag}"
    command:
      - -Xms${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMS:-512m}
      - -Xmx${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMX:-512m}
      - -Dcom.sun.management.jmxremote
      - -Dcom.sun.management.jmxremote.authenticate=false
      - -Dcom.sun.management.jmxremote.port=7199
      - -Dcom.sun.management.jmxremote.ssl=false
    environment:
      MINIO_HOST: rendering2-blob-storage
      MINIO_PORT: 9000
      RABBITMQ_HOST: rendering2-message-queue
      RABBITMQ_PORT: 5672
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379
      MONGODB_HOST: mongo-database
      MONGODB_PORT: 27017
      VIRTUAL_HOST: "${RENDERING2_SERVICE_PUBLIC_HOST:-rendering2.127.0.0.1.nip.io}:${RENDERING2_SERVICE_PUBLIC_PORT:-10100}"
      app.appId: rendering2
      app.public.protocol: "${RENDERING2_SERVICE_PUBLIC_PROTOCOL:-http}"
      app.public.host: "${RENDERING2_SERVICE_PUBLIC_HOST:-rendering2.127.0.0.1.nip.io}"
      app.public.port: "${RENDERING2_SERVICE_PUBLIC_PORT:-10100}"
      app.public.path: "${RENDERING2_SERVICE_PUBLIC_PATH:-}"
      app.internal.protocol: http
      app.internal.host: rendering2-service
      app.internal.port: 8080
      app.session.nodePermissionExpirationTime: "${RENDERING2_SERVICE_SESSION_NODE_PERMISSION_EXPIRATION_TIME:-60}"
      app.session.image.nodePermissionExpirationTime: "${RENDERING2_SERVICE_SESSION_IMAGE_NODE_PERMISSION_EXPIRATION_TIME:-}"
      app.session.audio.nodePermissionExpirationTime: "${RENDERING2_SERVICE_SESSION_AUDIO_NODE_PERMISSION_EXPIRATION_TIME:-}"
      app.session.video.nodePermissionExpirationTime: "${RENDERING2_SERVICE_SESSION_VIDEO_NODE_PERMISSION_EXPIRATION_TIME:-}"
      app.session.pdf.nodePermissionExpirationTime: "${RENDERING2_SERVICE_SESSION_PDF_NODE_PERMISSION_EXPIRATION_TIME:-}"
      app.session.moodle.nodePermissionExpirationTime: "${RENDERING2_SERVICE_SESSION_MOODLE_NODE_PERMISSION_EXPIRATION_TIME:-}"
      app.session.scorm.nodePermissionExpirationTime: "${RENDERING2_SERVICE_SESSION_SCORM_NODE_PERMISSION_EXPIRATION_TIME:-}"
      app.session.eduHtml.nodePermissionExpirationTime: "${RENDERING2_SERVICE_SESSION_EDUHTML_NODE_PERMISSION_EXPIRATION_TIME:-}"
      app.session.document.nodePermissionExpirationTime: "${RENDERING2_SERVICE_SESSION_DOCUMENT_NODE_PERMISSION_EXPIRATION_TIME:-}"
      app.session.spreadsheet.nodePermissionExpirationTime: "${RENDERING2_SERVICE_SESSION_SPREADSHEET_NODE_PERMISSION_EXPIRATION_TIME:-}"
      app.session.html.nodePermissionExpirationTime: "${RENDERING2_SERVICE_SESSION_HTML_NODE_PERMISSION_EXPIRATION_TIME:-}"
      app.session.h5p.nodePermissionExpirationTime: "${RENDERING2_SERVICE_SESSION_H5P_NODE_PERMISSION_EXPIRATION_TIME:-}"
      app.converter.image.format: "${RENDERING2_SERVICE_CONVERTER_IMAGE_FORMAT:-jpeg}"
      app.converter.image.mimeTypes: "${RENDERING2_SERVICE_CONVERTER_IMAGE_MIME_TYPES:-image/webp,image/jpeg,image/jpg,image/png,image/bmp}"
      app.converter.image.sizes: "${RENDERING2_SERVICE_CONVERTER_IMAGE_SIZES:-400,800}"
      app.converter.video.format: "${RENDERING2_SERVICE_CONVERTER_VIDEO_FORMAT:-mp4}"
      app.converter.video.mimeTypes: "${RENDERING2_SERVICE_CONVERTER_VIDEO_MIME_TYPES:-video/mp4,video/mpeg}"
      app.converter.video.resolutions: "${RENDERING2_SERVICE_CONVERTER_VIDEO_RESOLUTIONS:-480,720,1080}"
      app.converter.audio.mimeTypes: "${RENDERING2_SERVICE_CONVERTER_AUDIO_MIME_TYPES:-audio/mpeg,audio/mp4,audio/vnd.wav,audio/ogg,audio/vorbis}"
      app.converter.audio.bitrate: "${RENDERING2_SERVICE_CONVERTER_AUDIO_BITRATE:-160}"
      app.cache.cleaner.schedule: "${RENDERING2_SERVICE_CACHE_CLEANER_SCHEDULE:-6000000}"
      app.cache.cleaner.threshold.lower: "${RENDERING2_SERVICE_CACHE_CLEANER_THRESHOLD_LOWER:-0.9}"
      app.cache.cleaner.threshold.upper: "${RENDERING2_SERVICE_CACHE_CLEANER_THRESHOLD_UPPER:-0.7}"
      app.minio.user: "${RENDERING2_BLOB_STORAGE_USER:-rendering2}"
      app.minio.password: "${RENDERING2_BLOB_STORAGE_PASSWORD:-rendering2}"
      spring.rabbitmq.username: "${RENDERING2_MESSAGE_QUEUE_USER:-rendering}"
      spring.rabbitmq.password: "${RENDERING2_MESSAGE_QUEUE_PASSWORD:-rendering}"
      app.repository.registration.id.local.url: http://repository-service:8080/edu-sharing
      app.repository.registration.id.local.username: admin
      app.repository.registration.id.local.password: "${REPOSITORY_SERVICE_ADMIN_PASS:-admin}"
      app.security.adminPassword: admin
      spring.data.mongodb.authentication-database: ${RENDERING2_SERVICE_DATABASE_NAME:-rendering}
      spring.data.mongodb.username: "${RENDERING2_SERVICE_DATABASE_NAME:-rendering}"
      spring.data.mongodb.password: "${RENDERING2_SERVICE_DATABASE_USER:-rendering}"
      spring.data.mongodb.database: "${RENDERING2_SERVICE_DATABASES_PASS:-rendering}"
      app.moodle.host: "${RENDERING2_MOODLE_URL:-}"
      app.moodle.token: "${RENDERING2_MOODLE_TOKEN:-}"
      app.moodle.categoryid: "${RENDERING2_MOODLE_CATEGORY_ID:-1}"
      app.moodle.timeout-seconds: "${RENDERING2_MOODLE_TIMEOUT:-90}"
      app.lumi.host: http://rendering2-lumi:3000
      app.documentConverter.host: http://rendering2-document-converter:8080
    expose:
      - "8080"
    depends_on:
      - mongo-database
      - rendering2-message-queue
      - redis-cache
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING2_SERVICE_PORT_HTTP:-10100}:8080"

  rendering2-document-converter:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-build-document-converter:${docker.tag}"
    command:
      - -Xms${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMS:-512m}
      - -Xmx${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMX:-512m}
      - -Dcom.sun.management.jmxremote
      - -Dcom.sun.management.jmxremote.authenticate=false
      - -Dcom.sun.management.jmxremote.port=7199
      - -Dcom.sun.management.jmxremote.ssl=false
    expose:
      - "8080"

  rendering2-lumi:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-build-lumi:${docker.tag}"
    environment:
      AWS_ACCESS_KEY_ID: "${RENDERING2_BLOB_STORAGE_USER:-rendering}"
      AWS_SECRET_ACCESS_KEY: "${RENDERING2_BLOB_STORAGE_PASSWORD:-rendering}"
      MINIO_HOST: rendering2-blob-storage
      MINIO_PORT: 9000
      AWS_S3_MAX_FILE_LENGTH: 1000
      MONGODB_HOST: mongo-database
      MONGODB_PORT: 27017
      MONGODB_AUTH_DB: "${RENDERING2_LUMI_DATABASE_NAME:-lumi}"
      MONGODB_DB: "${RENDERING2_LUMI_DATABASE_NAME:-lumi}"
      MONGODB_USER: "${RENDERING2_LUMI_DATABASE_USER:-lumi}"
      MONGODB_PASSWORD: "${RENDERING2_LUMI_DATABASE_PASS:-lumi}"
      CONTENT_AWS_S3_BUCKET: contentbucket
      CONTENT_MONGO_COLLECTION: h5p
      TEMPORARY_AWS_S3_BUCKET: tempbucket
      LIBRARY_MONGO_COLLECTION: h5plibraries
      LIBRARY_AWS_S3_BUCKET: libbucket
      USERDATA_MONGO_COLLECTION: userdata
      FINISHED_MONGO_COLLECTION: finisheddata
      EDUSHARING_MONGO_COLLECTION: edusharing
      BASE_URL: /public/h5p
      CACHE: in-memory
    expose:
      - "3000"
volumes:
  rendering2-blob-storage-volume-data:
