version: '3.7'

services:
  rendering2-rustfs-storage:
    restart: unless-stopped

  rendering2-message-queue:
    restart: unless-stopped

  rendering2-service:
    restart: unless-stopped

  rendering2-lumi:
    restart: unless-stopped

  rendering2-document-converter:
    restart: unless-stopped
