version: '3.7'

services:

  rendering2-blob-storage:
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING2_BLOB_STORAGE_PORT:-9101}:9000"
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING2_BLOB_STORAGE_PORT:-9102}:9001"

  rendering2-message-queue:
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING2_MESSAGE_QUEUE_PORT:-9104}:5672"
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING2_MESSAGE_QUEUE_PORT:-9105}:15672"

  rendering2-service:
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING2_SERVICE_DEBUG_PORT:-9100}:8000"

  rendering2-document-converter:
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING2_DOCUMENT_CONVERTER_DEBUG_PORT:-9107}:8000"
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING2_DOCUMENT_CONVERTER_HTTP_PORT:-9110}:8080"

  rendering2-jupyter-converter:
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING2_JUPYTER_CONVERTER_HTTP_PORT:-9120}:8000"

  rendering2-lumi:
    environment:
      NODE_OPTS: "--inspect"
      LOG_SCOPE: "h5p:*"
      LOG_LEVEL: "debug"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING2_LUMI_DEBUG_PORT:-9108}:9229"
      - "${COMMON_BIND_HOST:-127.0.0.1}:${RENDERING2_LUMI_HTTP_PORT:-9112}:3000"

