apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-env
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
type: Opaque
data:
  "app.minio.user": {{ .Values.config.s3.username | b64enc | quote }}
  "app.minio.password": {{ default .Values.global.password .Values.config.s3.password | b64enc | quote }}
  "spring.rabbitmq.username": {{ .Values.config.rabbitmq.username | b64enc | quote }}
  "spring.rabbitmq.password": {{ default .Values.global.password .Values.config.rabbitmq.password | b64enc | quote }}
  {{- range $register := .Values.config.home.registrations }}
  {{- $modules := list -}}
  {{- range $module := $register.modules }}
  {{- $modules = append $modules $module.name }}
  {{- range $credential := $module.credentials }}
  "app.repository.registration.id.{{ $register.id }}.module.{{ $module.name }}.credentials.{{ $credential.name }}": {{ $credential.value | b64enc | quote }}
  {{- end }}
  {{- end }}
  "app.repository.registration.id.{{ $register.id }}.username": {{ $register.username | b64enc | quote }}
  "app.repository.registration.id.{{ $register.id }}.password": {{ (default $.Values.global.password $register.password) | b64enc | quote}}
  "app.repository.registration.id.{{ $register.id }}.optional-modules": {{ join "," $modules | b64enc | quote }}
  "app.repository.registration.id.{{ $register.id }}.url": {{ $register.url | b64enc | quote }}
  {{- end }}
  "app.security.adminPassword": {{ default .Values.global.password .Values.config.admin.password | b64enc | quote }}
  "spring.data.mongodb.uri": {{ (printf "mongodb://%s:%s@%s-0:%d,%s-1:%d,%s-2:%d/%s?authSource=admin" .Values.config.mongodb.username ((default .Values.global.password .Values.config.mongodb.password) | urlquery | replace "+" "%20") .Values.config.mongodb.host (.Values.config.mongodb.port | int) .Values.config.mongodb.host (.Values.config.mongodb.port | int) .Values.config.mongodb.host (.Values.config.mongodb.port | int) .Values.config.mongodb.database) | b64enc | quote }}
