apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
  ports:
  - name: http-api
    port: {{ .Values.service.port.api }}
    targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-headless
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
  ports:
  - name: http-api
    port: {{ .Values.service.port.api }}
{{- if .Values.global.metrics.servicemonitor.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-metrics-api
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
    app.kubernetes.io/component: "metrics-api"
spec:
  type: ClusterIP
  selector: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
  ports:
    - name: http-management
      port: {{ .Values.service.port.metrics.api }}
      targetPort: management
{{- if .Values.proxy.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-metrics-proxy
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
    app.kubernetes.io/component: "metrics-proxy"
spec:
  type: ClusterIP
  selector: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
  ports:
    - name: http-metrics-proxy
      port: {{ .Values.service.port.metrics.proxy }}
      targetPort: metrics-proxy
{{- end }}
{{- end }}
