apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "edusharing_common_lib.labels.app" . | nindent 6 }}
  serviceName: {{ include "edusharing_common_lib.names.name" . }}-headless
  template:
    metadata:
      labels: {{ include "edusharing_common_lib.labels.app" . | nindent 8 }}
      annotations:
        checksum/configmap-env: {{ include (print .Template.BasePath "/configmap-env.yaml") . | sha256sum | trunc 63 }}
        checksum/configmap-file: {{ include (print .Template.BasePath "/configmap-file.yaml") . | sha256sum | trunc 63 }}
        checksum/secret-env: {{ include (print .Template.BasePath "/secret-env.yaml") . | sha256sum | trunc 63 }}
        {{- if not .Values.global.metrics.servicemonitor.enabled }}
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "9080"
        prometheus.io/scrape: "true"
        {{- end }}
        sidecar.istio.io/inject: {{ .Values.global.cluster.istio.enabled | quote }}
        {{- with merge .Values.podAnnotations .Values.global.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ include "edusharing_common_lib.names.name" . }}
        image: {{ include "edusharing_common_lib.images.image" . }}{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_common_lib.names.name" . }}-env
        - secretRef:
            name: {{ include "edusharing_common_lib.names.name" . }}-env
        ports:
        - name: api
          containerPort: 8080
        - name: management
          containerPort: 9080
        {{- if default .Values.global.debug .Values.debug }}
        - name: jpda
          containerPort: 5005
        {{- end }}
        {{- with .Values.startupProbe }}
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: management
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: management
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: management
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{ if .Values.proxy.enabled }}
      - name: {{ include "edusharing_common_lib.names.name" . }}-proxy
        image: {{ include "edusharing_common_lib.images.common" . }}{{ .Values.sidecar.proxyCache.image.name }}:{{ .Values.sidecar.proxyCache.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        args:
          - '-F'
          - '-f'
          - /etc/varnish/default.vcl
          - '-T'
          - 127.0.0.1:6082
          - '-a'
          - 0.0.0.0:6081
        ports:
          - name: api-proxy
            containerPort: 6081
        volumeMounts:
          - name: file
            mountPath: /etc/varnish/default.vcl
            subPath: proxy-config
          - name: temp-proxy
            mountPath: /var/lib/varnish
        {{- with .Values.sidecar.proxyCache.startupProbe }}
        startupProbe:
          httpGet:
            path: /health/ready
            port: api-proxy
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.proxyCache.livenessProbe }}
        livenessProbe:
          exec:
            command:
              - /usr/bin/varnishadm
              - ping
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: 1
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.proxyCache.readinessProbe }}
        readinessProbe:
          httpGet:
            path: /health/ready
            port: api-proxy
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.proxyCache.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.sidecar.proxyCache.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      - name: {{ include "edusharing_common_lib.names.name" . }}-proxy-metrics
        image: {{ include "edusharing_common_lib.images.common" . }}{{ .Values.sidecar.proxyMetrics.image.name }}:{{ .Values.sidecar.proxyMetrics.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
          - name: metrics-proxy
            containerPort: 9131
        volumeMounts:
          - name: file
            mountPath: /etc/varnish/default.vcl
            subPath: proxy-config
          - name: temp-proxy
            mountPath: /var/lib/varnish
        {{- with .Values.sidecar.proxyMetrics.startupProbe }}
        startupProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "echo startupProbe > /dev/null"
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.proxyMetrics.livenessProbe }}
        livenessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "echo livenessProbe > /dev/null"
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.proxyMetrics.readinessProbe }}
        readinessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "echo readinessProbe > /dev/null"
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.proxyMetrics.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.sidecar.proxyMetrics.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with merge .Values.podSecurityContext .Values.global.security }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if or .Values.nodeAffinity .Values.podAntiAffinity }}
      affinity:
        {{- with .Values.nodeAffinity }}
        nodeAffinity: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.podAntiAffinity }}
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels: {{ include "edusharing_common_lib.labels.app" . | nindent 16 }}
          {{- else if eq .Values.podAntiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels: {{ include "edusharing_common_lib.labels.app" . | nindent 18 }}
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
      - name: file
        configMap:
          name: {{ include "edusharing_common_lib.names.name" . }}-file
      {{- if .Values.proxy.enabled }}
      - name: temp-proxy
        emptyDir: { }
      {{- end }}
