management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoints.web.exposure.include=health,metrics,prometheus
management.server.address=0.0.0.0
management.server.port=9080

app.security.allowedOrigins=

edu_sharing.basePath=http://repository.127.0.0.1.nip.io:8100/edu-sharing
edu_sharing.username=admin
edu_sharing.password=admin

edu_sharing.minio_url=http://127.0.0.1:9110
edu_sharing.minio_user=adminuser
edu_sharing.minio_password=adminpassword

edu_sharing.redis_url=localhost
edu_sharing.redis_port=6379

edu_sharing.queue.topicExchange=rendering_exchange

edu_sharing.queue.job.name=rendering_job_queue
edu_sharing.queue.job.key=rendering_job

edu_sharing.queue.image.name=image_job_queue
edu_sharing.queue.image.key=image_job

edu_sharing.queue.av.name=av_job_queue
edu_sharing.queue.av.key=av_job

edu_sharing.converted_image_mime_types=image/webp,image/jpeg,image/jpg,image/png,image/bmp
edu_sharing.image_format=jpeg

edu_sharing.converted_video_mime_types=video/mp4,video/mpeg
edu_sharing.video_format=mp4
edu_sharing.video_resolutions=480,720,1080
edu_sharing.image_sizes=400,800

spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/?authMechanism=DEFAULT
spring.data.mongodb.database=rendering
