app.security.allowedOrigins:*
app.security.enabled=false
app.repository.registration.enabled=false

app.repository.registration.id.local.url=http://repository.127.0.0.1.nip.io:8100/edu-sharing
app.repository.registration.id.local.username=admin
app.repository.registration.id.local.password=admin
app.repository.registration.id.local.optional-modules=H5P,JUPYTER,EDUHTML,BINDER
app.repository.registration.id.local.module.MOODLE.credentials.baseurl=baseurl
app.repository.registration.id.local.module.MOODLE.credentials.user=user
app.repository.registration.id.local.module.MOODLE.credentials.token=token
app.repository.registration.id.local.module.MOODLE.credentials.timeout=90
app.repository.registration.id.local.module.MOODLE.credentials.categoryid=1
#app.repository.registration.id.local.module.DDB.credentials.apiToken=API_TOKEN

app.repository.registration.id.local.module.BINDER.credentials.baseurl=https://edu-sharing.ingress.k8s.gwdg.de/binderhub/

app.documentConverter.host=http://localhost:9110
app.lumi.host=http://localhost:9112

app.minio.port=9101
app.minio.user=rendering2
app.minio.password=rendering2

spring.rabbitmq.port=9104
spring.rabbitmq.username=rendering
spring.rabbitmq.password=rendering

app.redis.port=9109

spring.data.mongodb.port=9106
spring.data.mongodb.authentication-database=rendering
spring.data.mongodb.database=rendering
spring.data.mongodb.username=rendering
spring.data.mongodb.password=rendering
