app.minio.host=${MINIO_HOST}
app.minio.port=${MINIO_PORT}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}

app.redis.host=${REDIS_HOST}
app.redis.port=${REDIS_PORT}

spring.data.mongodb.host=${MONGODB_HOST}
spring.data.mongodb.port=${MONGODB_PORT}
