management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoints.web.exposure.include=health,metrics,prometheus
management.server.address=0.0.0.0
management.server.port=9080

app.security.adminPassword=admin
app.security.allowedOrigins=*

app.security.enabled=true

app.cache.cleaner.schedule=6000000
app.cache.cleaner.threshold.lower=0.15
app.cache.cleaner.threshold.upper=0.25

app.session.nodePermissionExpirationTime=60
app.session.image.nodePermissionExpirationTime=
app.session.audio.nodePermissionExpirationTime=
app.session.video.nodePermissionExpirationTime=7200
app.session.pdf.nodePermissionExpirationTime=
app.session.moodle.nodePermissionExpirationTime=
app.session.scorm.nodePermissionExpirationTime=
app.session.eduHtml.nodePermissionExpirationTime=
app.session.document.nodePermissionExpirationTime=
app.session.spreadsheet.nodePermissionExpirationTime=
app.session.html.nodePermissionExpirationTime=
app.session.h5p.nodePermissionExpirationTime=

app.repository.registration.enabled=true

app.minio.protocol=http
app.minio.host=localhost
app.minio.port=9110
app.minio.url=${app.minio.protocol}://${app.minio.host}:${app.minio.port}
app.minio.user=adminuser
app.minio.password=adminpassword

app.storage.minio.bucket.mode=byType

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.redis.host=localhost
app.redis.port=6379

app.public.protocol=http
app.public.host=renderer2.192.168.178.29.nip.io
app.public.port=8080
app.public.path=/
app.public.url=${app.public.protocol}://${app.public.host}:${app.public.port}${app.public.path}

app.internal.protocol=${app.public.protocol}
app.internal.host=${app.public.host}
app.internal.port=${app.public.port}
app.internal.url=${app.internal.protocol}://${app.internal.host}:${app.internal.port}/

app.appId=rendering2
app.appCaption=I am the new renderer!

## Currently valid roles: master,controller,converter,avconverter,job-manager
## Only one master per cluster is allowed
## Leave empty for all roles (or specify all)
app.roles=master,controller,converter,avconverter,job-manager

app.queue.topicExchange=rendering_exchange

app.queue.job.name=rendering_job_queue
app.queue.job.key=rendering_job

app.queue.image.name=image_job_queue
app.queue.image.key=image_job

app.queue.av.name=av_job_queue
app.queue.av.key=av_job

app.queue.moodle.name=moodle_job_queue
app.queue.moodle.key=moodle_job

app.queue.eduHtml.name=edu_html_job_queue
app.queue.eduHtml.key=edu_html_job

app.queue.h5p.name=h5p_job_queue
app.queue.h5p.key=h5p_job

app.queue.document.name=document_job_queue
app.queue.document.key=document_job

app.queue.jupyter.name=jupyter_job_queue
app.queue.jupyter.key=jupyter_job

app.converter.image.format=jpeg
app.converter.image.mimeTypes=image/webp,image/jpeg,image/jpg,image/png,image/bmp
app.converter.image.sizes=400,800

app.converter.spreadsheetToHtml.enabled=true

app.converter.video.format=mp4
app.converter.video.mimeTypes=video/mp4,video/mpeg
app.converter.video.resolutions.480.priority=2
app.converter.video.resolutions.720.priority=1
app.converter.video.resolutions.1080.priority=0


app.converter.audio.mimeTypes=audio/mpeg,audio/mp4,audio/vnd.wav,audio/ogg,audio/vorbis
app.converter.audio.bitrate=160

app.moodle.host=
app.moodle.token=
app.moodle.categoryid=1
app.moodle.timeout-seconds=90

app.lumi.host=http://localhost:3000

app.documentConverter.host=http://localhost:8081
app.jupyterConverter.host=http://127.0.0.1:8000

app.asset.static.frameAncestors=*

spring.data.mongodb.authentication-database=admin
spring.data.mongodb.host=localhost
spring.data.mongodb.username=admin
spring.data.mongodb.password=admin
spring.data.mongodb.database=rendering
spring.data.mongodb.auto-index-creation=true

## logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

server.servlet.session.cookie.same-site=none
