app.s3.host=${S3_HOST}
app.s3.port=${S3_PORT}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}

spring.redis.standalone.host=${REDIS_HOST}
spring.redis.standalone.port=${REDIS_PORT}

spring.mongodb.host=${MONGODB_HOST}
spring.mongodb.port=${MONGODB_PORT}
