app.security.enabled=true
app.repository.registration.enabled=true

logging.level.org.springframework.security=DEBUG


app.repository.registration.id.local.url=http://repository.127.0.0.1.nip.io:8100/edu-sharing
app.repository.registration.id.local.username=admin
app.repository.registration.id.local.password=admin
app.repository.registration.id.local.optional-modules=H5P,JUPYTER,EDUHTML,BINDER
app.repository.registration.id.local.module.MOODLE.credentials.baseurl=baseurl
app.repository.registration.id.local.module.MOODLE.credentials.user=user
app.repository.registration.id.local.module.MOODLE.credentials.token=token
app.repository.registration.id.local.module.MOODLE.credentials.timeout=90
app.repository.registration.id.local.module.MOODLE.credentials.categoryid=1
#app.repository.registration.id.local.module.DDB.credentials.apiToken=API_TOKEN

app.repository.registration.id.local.module.ONYX.credentials.onyxrunurl=http://localhost:15100/onyxplayer/onyxrun
app.repository.registration.id.local.module.ONYX.credentials.onyxresturl=http://localhost:15100/onyxplayer/rest/run
app.repository.registration.id.local.module.ONYX.credentials.returnservice=preview

app.repository.registration.id.local.module.BINDER.credentials.baseurl=http://localhost:8585/binderhub/
app.repository.registration.id.local.module.BINDER.credentials.githubtoken=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

app.documentConverter.host=http://localhost:9110
app.lumi.host=http://localhost:9112

app.minio.port=9101
app.minio.user=rendering2
app.minio.password=rendering2

spring.rabbitmq.port=9104
spring.rabbitmq.username=rendering
spring.rabbitmq.password=rendering

spring.redis.standalone.port=9109

spring.data.mongodb.port=9106
spring.data.mongodb.authentication-database=rendering
spring.data.mongodb.database=rendering
spring.data.mongodb.username=rendering
spring.data.mongodb.password=rendering

logging.level.org.edu_sharing.rendering.core.dto.ErrorMessage=INFO

