spring.application.name=edu-sharing community services document converter

jodconverter.local.enabled=true

app.supportedExtensions=doc,docx,ppt,pptx,xls,xlsx,odt,odp,ods

spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB