apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-env
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
data:
  AWS_S3_MAX_FILE_LENGTH: {{ .Values.config.files.maxsize | quote }}
  AWS_S3_ENDPOINT: {{ (printf "%s://%s:%d" .Values.config.s3.protocol .Values.config.s3.host (.Values.config.s3.port | int)) | quote }}
  AWS_S3_REGION: {{ .Values.config.s3.region | quote }}
  AWS_S3_TRUST_ALL_CERTIFICATES: {{ .Values.config.s3.trustAllCertificates | quote }}
  AWS_S3_CHECKSUM_CALCULATION_WHEN_REQUIRED: {{ .Values.config.s3.checksumCalculationWhenRequired | quote }}
  AWS_S3_MAX_SOCKETS: {{ .Values.config.s3.maxSockets | quote }}
  AWS_S3_CONNECTION_TIMEOUT_MS: {{ .Values.config.s3.connectionTimeoutMs | quote }}
  AWS_S3_REQUEST_TIMEOUT_MS: {{ .Values.config.s3.requestTimeoutMs | quote }}
  BASE_URL: {{ printf "%s/public/h5p" .Values.config.base | quote }}
  CACHE: {{ .Values.config.cache.type | quote }}
  CONTENT_AWS_S3_BUCKET: {{ .Values.config.s3.buckets.content | quote }}
  CONTENT_MONGO_COLLECTION: {{ .Values.config.mongodb.collections.content | quote }}
  EDUSHARING_MONGO_COLLECTION: {{ .Values.config.mongodb.collections.edusharing | quote }}
  LIBRARY_AWS_S3_BUCKET: {{ .Values.config.s3.buckets.library | quote }}
  LIBRARY_MONGO_COLLECTION: {{ .Values.config.mongodb.collections.library | quote }}
  LOG_LEVEL: {{ .Values.config.log.level | quote }}
  LOG_SCOPE: {{ .Values.config.log.scope | quote }}
  S3_HOST: {{ .Values.config.s3.host | quote }}
  S3_PORT: {{ .Values.config.s3.port | quote }}
  MONGODB_HOST: {{ (printf "%s-0" .Values.config.mongodb.host) | quote }}
  MONGODB_PORT: {{ .Values.config.mongodb.port | quote }}
  TEMPORARY_AWS_S3_BUCKET: {{ .Values.config.s3.buckets.temporary | quote }}
  DEBUG: {{ .Values.config.log.scope | quote }}
