apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-env
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.config.s3.username | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ default .Values.global.password .Values.config.s3.password | b64enc | quote }}
  MONGODB_URL: {{ (printf "mongodb://%s:%s@%s-0:%d,%s-1:%d,%s-2:%d/%s" .Values.config.mongodb.username (default .Values.global.password .Values.config.mongodb.password) .Values.config.mongodb.host (.Values.config.mongodb.port | int) .Values.config.mongodb.host (.Values.config.mongodb.port | int) .Values.config.mongodb.host (.Values.config.mongodb.port | int) .Values.config.mongodb.database) | b64enc | quote }}
