package org.edu_sharing.rendering.core

object ErrorStrings {
    const val ERROR_PROCESSING_JOB = "RENDERING.ERROR.ERROR_PROCESSING_JOB"
    const val GENERIC_CONVERSION_ERROR = "RENDERING.ERROR.GENERIC_CONVERSION_ERROR"
    const val GENERIC_NOT_FOUND = "RENDERING.ERROR.GENERIC_NOT_FOUND"
    const val GENERIC_BAD_REQUEST = "RENDERING.ERROR.GENERIC_BAD_REQUEST"
    const val GENERIC_MODULE_NOT_AVAILABLE = "RENDERING.ERROR.GENERIC_MODULE_NOT_AVAILABLE"
    const val GENERIC_OBJECT_NOT_SUPPORTED = "RENDERING.ERROR.GENERIC_OBJECT_NOT_SUPPORTED"
    const val GENERIC_ACCESS_DENIED = "RENDERING.ERROR.GENERIC_ACCESS_DENIED"
    const val GENERIC_INTERNAL_SERVER_ERROR = "RENDERING.ERROR.GENERIC_INTERNAL_SERVER_ERROR"

    /** The H5P package exceeds a size limit of lumi (unpacked size or a single file). */
    const val H5P_PACKAGE_TOO_LARGE = "RENDERING.ERROR.H5P_PACKAGE_TOO_LARGE"

    /** lumi rejected the H5P package as such: not a zip, a file type that is not allowed, a broken h5p.json, ... */
    const val H5P_PACKAGE_INVALID = "RENDERING.ERROR.H5P_PACKAGE_INVALID"
}